---
- hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: List upgradable packages
      shell: apt list --upgradable 2>/dev/null | grep -v "Listing..."
      register: upgrade_list
      changed_when: false

    - name: Show packages that can be upgraded
      debug:
        msg: "{{ upgrade_list.stdout_lines }}"

