---
- hosts: all
  become: true

  tasks:
    - name: Update and upgrade all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot the systems
      command: /sbin/shutdown -r now
